### ISSUE TITLE
Prophet can't be found in grid.py

### ISSUE THREAD

**Issue by amengjiao** [mikekeith52/scalecast#55] opened 2023-07-01 00:57 UTC
Hello! I am running this code below from your medium article: https://towardsdatascience.com/introducing-scalecast-a-forecasting-library-pt-1-33b556d9b019

f.set_validation_length(6)
# automatically tune and forecast with a series of models
models = ('mlr','knn','svr','xgboost','gbt','elasticnet','mlp', 'arima','prophet' )
for m in models:
 f.set_estimator(m)
 f.tune() # by default, will pull grids from Grids.py
 f.auto_forecast()

I got this error: ModuleNotFoundError: No module named 'prophet'

**Comment by mikekeith52** [comment] 2023-07-02 15:47
This looks like a bug. Give me second to look into it.

**Comment by mikekeith52** [comment] 2023-07-04 01:36
I was able to reproduce the error and found the source of the issue. In the next update, this will be fixed. I could probably commit a new version today or tomorrow.

**Comment by mikekeith52** [comment] 2023-08-03 21:18
Hi, this should be fixed with the new version of scalecast. Please upgrade is you have not already:

`pip install --upgrade scalecast`

Thanks for raising the issue!

**Closed by mikekeith52** 2023-08-03 21:18 UTC
Labels: bug
